codex-bot/github

github/commands/start.py
github/config.py.sample
github/data_types/issue.py
github/data_types/repository.py
github/data_types/user.py
github/events/base.py
github/events/issues.py
github/main.py

Closes #13 
- Пока не работает html markdown, требуется доработка ядра
- Нет emoji

Issue Event implement

---

github/data_types/branch.py
github/data_types/pull_request.py
github/events/issues.py
github/events/pull_request.py
github/main.py

Pull Request event

---

github/events/push.py

Create or delete branch event push  filter

---

github/events/issues.py
github/events/pull_request.py
github/events/push.py

Fix HTML tags

---

github/events/push.py

Import html, remove await somewhere

---

github/events/pull_request_review.py

Update PullRequestReview event process

---

github/events/watch.py
github/main.py

Star event

---

github/classes/chat_controller.py
github/commands/link.py
github/commands/start.py
github/main.py

GithubLink

---

github/events/fork.py
github/main.py

Add fork event. Close #58

---

github/classes/chat_controller.py
github/commands/branch.py
github/commands/link.py
github/commands/start.py
github/events/fork.py
github/events/issues.py
github/events/ping.py
github/events/pull_request.py
github/events/pull_request_review.py
github/events/push.py
github/events/watch.py
github/main.py

Allows to control which branch will trigger notification.
Also fix created_branch notification failure
close #28

Add /github_branch command.

---

.gitmodules

close https://github.com/codex-team/codex.bot/issues/70

Gitmodules fix

---

github/events/pull_request_review.py
github/main.py

Check if request review body is empty

---

github/events/pull_request_review.py

Remove 2 linebreaks on empty body

---

github/data_types/organization.py
github/events/ping.py

Now webhook from organization is supported for Ping event
https://docs.github.com/en/rest/reference/orgs

Add organization data type and init support of ping event

---

github/data_types/organization.py
github/events/ping.py
github/events/repository.py
github/main.py

Now, when someone creates a repository in an organization, we will get and process a repository event and send a notification

Repository event support

---

.github/workflows/build-and-push-docker-image.yml
Dockerfile

Issues #100  and #99  were closed on this request. Added file for github actions and changed docker file to copy all sources to it

Added COPY to dockerfile and git action

---

Dockerfile

Added CMD command into Dockerfile for working with Kubernetes

Added CMD command into Dockerfile

---

github/data_types/category.py
github/data_types/discussion.py
github/events/discussions.py
github/main.py

Added triggers for discussions

---

github/events/repository.py

Fixed bug with renamed and deleted repo in organization

---

github/data_types/discussion_comment.py
github/events/discussion_comment.py
github/main.py

Added supporting of discussion comments

Added triggers for discussion comments
